kind: common.Repository
spec:
  mainBranch: v2
---
kind: common.Docker
name: setup-ci
spec:
    allowInsecure: true

---
kind: golang.Toolchain
spec:
    extraPackages:
        - cdrkit
        - cryptsetup
        - dosfstools
        - e2fsprogs
        - gptfdisk
        - lvm2
        - parted
        - util-linux
        - squashfs-tools
        - xfsprogs
---
kind: service.CodeCov
spec:
  targetThreshold: 35
---
kind: auto.CustomSteps
spec:
  steps:
    - name: zfs-img
      toplevel: true
---
kind: custom.Step
name: zfs-img
spec:
  makefile:
    enabled: true
  docker:
    enabled: true
    stages:
      - name: zfs-img-gen
        description: Creates the ZFS image
        from: fedora:39
        steps:
          - script:
              command: dnf install -y zfs-fuse zstd && rm -rf /var/cache/dnf
          - script:
              command: |
                --security=insecure zfs-fuse & \
                dd if=/dev/zero of=/tmp/zfs.img bs=16M count=4 iflag=fullblock && \
                sleep 1 && \
                zpool create -f -R /tmp/zfs zroot1 /tmp/zfs.img && \
                zstd -19 /tmp/zfs.img -o /tmp/zfs.img.zst
      - name: zfs-img
        description: copies out the ZFS image
        steps:
          - copy:
              from: zfs-img-gen
              src: /tmp/zfs.img.zst
              dst: /
---
kind: golang.UnitTests
name: unit-tests
spec:
    requiresInsecure: true
    docker:
      steps:
        - copy:
            from: zfs-img
            src: /
            dst: /src/blkid/testdata/
