// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg dmioctl -struct Header -input header.h -endianness NativeEndian"; DO NOT EDIT.

package dmioctl

import "encoding/binary"

var _ = binary.NativeEndian

// Header is a byte slice representing the header.h C header.
type Header []byte

// Get_version_major returns version_major.
func (s Header) Get_version_major() uint32 {
	return binary.NativeEndian.Uint32(s[0:4])
}

// Put_version_major sets version_major.
func (s Header) Put_version_major(v uint32) {
	binary.NativeEndian.PutUint32(s[0:4], v)
}

// Get_version_minor returns version_minor.
func (s Header) Get_version_minor() uint32 {
	return binary.NativeEndian.Uint32(s[4:8])
}

// Put_version_minor sets version_minor.
func (s Header) Put_version_minor(v uint32) {
	binary.NativeEndian.PutUint32(s[4:8], v)
}

// Get_version_patch returns version_patch.
func (s Header) Get_version_patch() uint32 {
	return binary.NativeEndian.Uint32(s[8:12])
}

// Put_version_patch sets version_patch.
func (s Header) Put_version_patch(v uint32) {
	binary.NativeEndian.PutUint32(s[8:12], v)
}

// Get_data_size returns total size of data passed in including this struct.
func (s Header) Get_data_size() uint32 {
	return binary.NativeEndian.Uint32(s[12:16])
}

// Put_data_size sets total size of data passed in including this struct.
func (s Header) Put_data_size(v uint32) {
	binary.NativeEndian.PutUint32(s[12:16], v)
}

// Get_data_start returns offset to start of data relative to start of this struct.
func (s Header) Get_data_start() uint32 {
	return binary.NativeEndian.Uint32(s[16:20])
}

// Put_data_start sets offset to start of data relative to start of this struct.
func (s Header) Put_data_start(v uint32) {
	binary.NativeEndian.PutUint32(s[16:20], v)
}

// Get_target_count returns in/out.
func (s Header) Get_target_count() uint32 {
	return binary.NativeEndian.Uint32(s[20:24])
}

// Put_target_count sets in/out.
func (s Header) Put_target_count(v uint32) {
	binary.NativeEndian.PutUint32(s[20:24], v)
}

// Get_open_count returns out.
func (s Header) Get_open_count() uint32 {
	return binary.NativeEndian.Uint32(s[24:28])
}

// Put_open_count sets out.
func (s Header) Put_open_count(v uint32) {
	binary.NativeEndian.PutUint32(s[24:28], v)
}

// Get_flags returns in/out.
func (s Header) Get_flags() uint32 {
	return binary.NativeEndian.Uint32(s[28:32])
}

// Put_flags sets in/out.
func (s Header) Put_flags(v uint32) {
	binary.NativeEndian.PutUint32(s[28:32], v)
}

// Get_event_nr returns in/out.
func (s Header) Get_event_nr() uint32 {
	return binary.NativeEndian.Uint32(s[32:36])
}

// Put_event_nr sets in/out.
func (s Header) Put_event_nr(v uint32) {
	binary.NativeEndian.PutUint32(s[32:36], v)
}

// Get_padding returns padding.
func (s Header) Get_padding() uint32 {
	return binary.NativeEndian.Uint32(s[36:40])
}

// Put_padding sets padding.
func (s Header) Put_padding(v uint32) {
	binary.NativeEndian.PutUint32(s[36:40], v)
}

// Get_dev returns in/out.
func (s Header) Get_dev() uint64 {
	return binary.NativeEndian.Uint64(s[40:48])
}

// Put_dev sets in/out.
func (s Header) Put_dev(v uint64) {
	binary.NativeEndian.PutUint64(s[40:48], v)
}

// Get_name returns device name.
func (s Header) Get_name() []byte {
	return s[48:176]
}

// Put_name sets device name.
func (s Header) Put_name(v []byte) {
	copy(s[48:176], v)
}

// Get_uuid returns unique identifier for the block device.
func (s Header) Get_uuid() []byte {
	return s[176:305]
}

// Put_uuid sets unique identifier for the block device.
func (s Header) Put_uuid(v []byte) {
	copy(s[176:305], v)
}

// Get_data returns padding or data.
func (s Header) Get_data() []byte {
	return s[305:312]
}

// Put_data sets padding or data.
func (s Header) Put_data(v []byte) {
	copy(s[305:312], v)
}

// HEADER_SIZE is the size of the Header struct.
const HEADER_SIZE = 312
