// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg dmioctl -struct NameList -input namelist.h -endianness NativeEndian"; DO NOT EDIT.

package dmioctl

import "encoding/binary"

var _ = binary.NativeEndian

// NameList is a byte slice representing the namelist.h C header.
type NameList []byte

// Get_dev returns dev.
func (s NameList) Get_dev() uint64 {
	return binary.NativeEndian.Uint64(s[0:8])
}

// Put_dev sets dev.
func (s NameList) Put_dev(v uint64) {
	binary.NativeEndian.PutUint64(s[0:8], v)
}

// Get_next returns offset to the next record from the start of this one.
func (s NameList) Get_next() uint32 {
	return binary.NativeEndian.Uint32(s[8:12])
}

// Put_next sets offset to the next record from the start of this one.
func (s NameList) Put_next(v uint32) {
	binary.NativeEndian.PutUint32(s[8:12], v)
}

// NAMELIST_SIZE is the size of the NameList struct.
const NAMELIST_SIZE = 12
