// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg dmioctl -struct Spec -input spec.h -endianness NativeEndian"; DO NOT EDIT.

package dmioctl

import "encoding/binary"

var _ = binary.NativeEndian

// Spec is a byte slice representing the spec.h C header.
type Spec []byte

// Get_sector_start returns sector_start.
func (s Spec) Get_sector_start() uint64 {
	return binary.NativeEndian.Uint64(s[0:8])
}

// Put_sector_start sets sector_start.
func (s Spec) Put_sector_start(v uint64) {
	binary.NativeEndian.PutUint64(s[0:8], v)
}

// Get_length returns length.
func (s Spec) Get_length() uint64 {
	return binary.NativeEndian.Uint64(s[8:16])
}

// Put_length sets length.
func (s Spec) Put_length(v uint64) {
	binary.NativeEndian.PutUint64(s[8:16], v)
}

// Get_status returns used when reading from kernel only.
func (s Spec) Get_status() uint32 {
	return binary.NativeEndian.Uint32(s[16:20])
}

// Put_status sets used when reading from kernel only.
func (s Spec) Put_status(v uint32) {
	binary.NativeEndian.PutUint32(s[16:20], v)
}

// Get_next returns offset in bytes to the next target_spec.
func (s Spec) Get_next() uint32 {
	return binary.NativeEndian.Uint32(s[20:24])
}

// Put_next sets offset in bytes to the next target_spec.
func (s Spec) Put_next(v uint32) {
	binary.NativeEndian.PutUint32(s[20:24], v)
}

// Get_target_type returns target_type.
func (s Spec) Get_target_type() []byte {
	return s[24:40]
}

// Put_target_type sets target_type.
func (s Spec) Put_target_type(v []byte) {
	copy(s[24:40], v)
}

// SPEC_SIZE is the size of the Spec struct.
const SPEC_SIZE = 40
