// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg squashfs -struct SuperBlock -input superblock.h -endianness LittleEndian"; DO NOT EDIT.

package squashfs

import "encoding/binary"

var _ = binary.LittleEndian

// SuperBlock is a byte slice representing the superblock.h C header.
type SuperBlock []byte

// Get_magic returns magic.
func (s SuperBlock) Get_magic() uint32 {
	return binary.LittleEndian.Uint32(s[0:4])
}

// Get_inode_count returns inode_count.
func (s SuperBlock) Get_inode_count() uint32 {
	return binary.LittleEndian.Uint32(s[4:8])
}

// Get_mod_time returns mod_time.
func (s SuperBlock) Get_mod_time() uint32 {
	return binary.LittleEndian.Uint32(s[8:12])
}

// Get_block_size returns block_size.
func (s SuperBlock) Get_block_size() uint32 {
	return binary.LittleEndian.Uint32(s[12:16])
}

// Get_frag_count returns frag_count.
func (s SuperBlock) Get_frag_count() uint32 {
	return binary.LittleEndian.Uint32(s[16:20])
}

// Get_compressor returns compressor.
func (s SuperBlock) Get_compressor() uint16 {
	return binary.LittleEndian.Uint16(s[20:22])
}

// Get_block_log returns block_log.
func (s SuperBlock) Get_block_log() uint16 {
	return binary.LittleEndian.Uint16(s[22:24])
}

// Get_flags returns flags.
func (s SuperBlock) Get_flags() uint16 {
	return binary.LittleEndian.Uint16(s[24:26])
}

// Get_id_count returns id_count.
func (s SuperBlock) Get_id_count() uint16 {
	return binary.LittleEndian.Uint16(s[26:28])
}

// Get_version_major returns version_major.
func (s SuperBlock) Get_version_major() uint16 {
	return binary.LittleEndian.Uint16(s[28:30])
}

// Get_version_minor returns version_minor.
func (s SuperBlock) Get_version_minor() uint16 {
	return binary.LittleEndian.Uint16(s[30:32])
}

// Get_root_inode returns root_inode.
func (s SuperBlock) Get_root_inode() uint64 {
	return binary.LittleEndian.Uint64(s[32:40])
}

// Get_bytes_used returns bytes_used.
func (s SuperBlock) Get_bytes_used() uint64 {
	return binary.LittleEndian.Uint64(s[40:48])
}

// Get_id_table returns id_table.
func (s SuperBlock) Get_id_table() uint64 {
	return binary.LittleEndian.Uint64(s[48:56])
}

// Get_xattr_table returns xattr_table.
func (s SuperBlock) Get_xattr_table() uint64 {
	return binary.LittleEndian.Uint64(s[56:64])
}

// Get_inode_table returns inode_table.
func (s SuperBlock) Get_inode_table() uint64 {
	return binary.LittleEndian.Uint64(s[64:72])
}

// Get_dir_table returns dir_table.
func (s SuperBlock) Get_dir_table() uint64 {
	return binary.LittleEndian.Uint64(s[72:80])
}

// Get_frag_table returns frag_table.
func (s SuperBlock) Get_frag_table() uint64 {
	return binary.LittleEndian.Uint64(s[80:88])
}

// Get_export_table returns export_table.
func (s SuperBlock) Get_export_table() uint64 {
	return binary.LittleEndian.Uint64(s[88:96])
}

// SUPERBLOCK_SIZE is the size of the SuperBlock struct.
const SUPERBLOCK_SIZE = 96
