// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg vmfs -struct FSInfo -input vmfs_fs.h -endianness LittleEndian"; DO NOT EDIT.

package vmfs

import "encoding/binary"

var _ = binary.LittleEndian

// FSInfo is a byte slice representing the vmfs_fs.h C header.
type FSInfo []byte

// Get_magic returns magic.
func (s FSInfo) Get_magic() uint32 {
	return binary.LittleEndian.Uint32(s[0:4])
}

// Put_magic sets magic.
func (s FSInfo) Put_magic(v uint32) {
	binary.LittleEndian.PutUint32(s[0:4], v)
}

// Get_volume_version returns volume_version.
func (s FSInfo) Get_volume_version() uint32 {
	return binary.LittleEndian.Uint32(s[4:8])
}

// Put_volume_version sets volume_version.
func (s FSInfo) Put_volume_version(v uint32) {
	binary.LittleEndian.PutUint32(s[4:8], v)
}

// Get_version returns version.
func (s FSInfo) Get_version() byte {
	return s[8]
}

// Put_version sets version.
func (s FSInfo) Put_version(v byte) {
	s[8] = v
}

// Get_uuid returns uuid.
func (s FSInfo) Get_uuid() []byte {
	return s[9:25]
}

// Put_uuid sets uuid.
func (s FSInfo) Put_uuid(v []byte) {
	copy(s[9:25], v)
}

// Get_mode returns mode.
func (s FSInfo) Get_mode() uint32 {
	return binary.LittleEndian.Uint32(s[25:29])
}

// Put_mode sets mode.
func (s FSInfo) Put_mode(v uint32) {
	binary.LittleEndian.PutUint32(s[25:29], v)
}

// Get_label returns label.
func (s FSInfo) Get_label() []byte {
	return s[29:157]
}

// Put_label sets label.
func (s FSInfo) Put_label(v []byte) {
	copy(s[29:157], v)
}

// FSINFO_SIZE is the size of the FSInfo struct.
const FSINFO_SIZE = 157
