// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg vmfs -struct VolumeInfo -input vmfs_volume.h -endianness LittleEndian"; DO NOT EDIT.

package vmfs

import "encoding/binary"

var _ = binary.LittleEndian

// VolumeInfo is a byte slice representing the vmfs_volume.h C header.
type VolumeInfo []byte

// Get_magic returns magic.
func (s VolumeInfo) Get_magic() uint32 {
	return binary.LittleEndian.Uint32(s[0:4])
}

// Put_magic sets magic.
func (s VolumeInfo) Put_magic(v uint32) {
	binary.LittleEndian.PutUint32(s[0:4], v)
}

// Get_ver returns ver.
func (s VolumeInfo) Get_ver() uint32 {
	return binary.LittleEndian.Uint32(s[4:8])
}

// Put_ver sets ver.
func (s VolumeInfo) Put_ver(v uint32) {
	binary.LittleEndian.PutUint32(s[4:8], v)
}

// Get_irrelevant returns irrelevant.
func (s VolumeInfo) Get_irrelevant() []byte {
	return s[8:130]
}

// Put_irrelevant sets irrelevant.
func (s VolumeInfo) Put_irrelevant(v []byte) {
	copy(s[8:130], v)
}

// Get_uuid returns uuid.
func (s VolumeInfo) Get_uuid() []byte {
	return s[130:146]
}

// Put_uuid sets uuid.
func (s VolumeInfo) Put_uuid(v []byte) {
	copy(s[130:146], v)
}

// VOLUMEINFO_SIZE is the size of the VolumeInfo struct.
const VOLUMEINFO_SIZE = 146
