// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg xfs -struct SuperBlock -input superblock.h -endianness BigEndian"; DO NOT EDIT.

package xfs

import "encoding/binary"

var _ = binary.BigEndian

// SuperBlock is a byte slice representing the superblock.h C header.
type SuperBlock []byte

// Get_sb_magicnum returns magic number == XFS_SB_MAGIC.
func (s SuperBlock) Get_sb_magicnum() uint32 {
	return binary.BigEndian.Uint32(s[0:4])
}

// Get_sb_blocksize returns logical block size, bytes.
func (s SuperBlock) Get_sb_blocksize() uint32 {
	return binary.BigEndian.Uint32(s[4:8])
}

// Get_sb_dblocks returns number of data blocks.
func (s SuperBlock) Get_sb_dblocks() uint64 {
	return binary.BigEndian.Uint64(s[8:16])
}

// Get_sb_rblocks returns number of realtime blocks.
func (s SuperBlock) Get_sb_rblocks() uint64 {
	return binary.BigEndian.Uint64(s[16:24])
}

// Get_sb_rextents returns number of realtime extents.
func (s SuperBlock) Get_sb_rextents() uint64 {
	return binary.BigEndian.Uint64(s[24:32])
}

// Get_sb_uuid returns file system unique id.
func (s SuperBlock) Get_sb_uuid() []byte {
	return s[32:48]
}

// Get_sb_logstart returns starting block of log if internal.
func (s SuperBlock) Get_sb_logstart() uint64 {
	return binary.BigEndian.Uint64(s[48:56])
}

// Get_sb_rootino returns root inode number.
func (s SuperBlock) Get_sb_rootino() uint64 {
	return binary.BigEndian.Uint64(s[56:64])
}

// Get_sb_rbmino returns bitmap inode for realtime extents.
func (s SuperBlock) Get_sb_rbmino() uint64 {
	return binary.BigEndian.Uint64(s[64:72])
}

// Get_sb_rsumino returns summary inode for rt bitmap.
func (s SuperBlock) Get_sb_rsumino() uint64 {
	return binary.BigEndian.Uint64(s[72:80])
}

// Get_sb_rextsize returns realtime extent size, blocks.
func (s SuperBlock) Get_sb_rextsize() uint32 {
	return binary.BigEndian.Uint32(s[80:84])
}

// Get_sb_agblocks returns size of an allocation group.
func (s SuperBlock) Get_sb_agblocks() uint32 {
	return binary.BigEndian.Uint32(s[84:88])
}

// Get_sb_agcount returns number of allocation groups.
func (s SuperBlock) Get_sb_agcount() uint32 {
	return binary.BigEndian.Uint32(s[88:92])
}

// Get_sb_rbmblocks returns number of rt bitmap blocks.
func (s SuperBlock) Get_sb_rbmblocks() uint32 {
	return binary.BigEndian.Uint32(s[92:96])
}

// Get_sb_logblocks returns number of log blocks.
func (s SuperBlock) Get_sb_logblocks() uint32 {
	return binary.BigEndian.Uint32(s[96:100])
}

// Get_sb_versionnum returns header version == XFS_SB_VERSION.
func (s SuperBlock) Get_sb_versionnum() uint16 {
	return binary.BigEndian.Uint16(s[100:102])
}

// Get_sb_sectsize returns volume sector size, bytes.
func (s SuperBlock) Get_sb_sectsize() uint16 {
	return binary.BigEndian.Uint16(s[102:104])
}

// Get_sb_inodesize returns inode size, bytes.
func (s SuperBlock) Get_sb_inodesize() uint16 {
	return binary.BigEndian.Uint16(s[104:106])
}

// Get_sb_inopblock returns inodes per block.
func (s SuperBlock) Get_sb_inopblock() uint16 {
	return binary.BigEndian.Uint16(s[106:108])
}

// Get_sb_fname returns file system name.
func (s SuperBlock) Get_sb_fname() []byte {
	return s[108:120]
}

// Get_sb_blocklog returns log2 of sb_blocksize.
func (s SuperBlock) Get_sb_blocklog() byte {
	return s[120]
}

// Get_sb_sectlog returns log2 of sb_sectsize.
func (s SuperBlock) Get_sb_sectlog() byte {
	return s[121]
}

// Get_sb_inodelog returns log2 of sb_inodesize.
func (s SuperBlock) Get_sb_inodelog() byte {
	return s[122]
}

// Get_sb_inopblog returns log2 of sb_inopblock.
func (s SuperBlock) Get_sb_inopblog() byte {
	return s[123]
}

// Get_sb_agblklog returns log2 of sb_agblocks (rounded up).
func (s SuperBlock) Get_sb_agblklog() byte {
	return s[124]
}

// Get_sb_rextslog returns log2 of sb_rextents.
func (s SuperBlock) Get_sb_rextslog() byte {
	return s[125]
}

// Get_sb_inprogress returns mkfs is in progress, don't mount.
func (s SuperBlock) Get_sb_inprogress() byte {
	return s[126]
}

// Get_sb_imax_pct returns max % of fs for inode space.
func (s SuperBlock) Get_sb_imax_pct() byte {
	return s[127]
}

// Get_sb_icount returns allocated inodes.
func (s SuperBlock) Get_sb_icount() uint64 {
	return binary.BigEndian.Uint64(s[128:136])
}

// Get_sb_ifree returns free inodes.
func (s SuperBlock) Get_sb_ifree() uint64 {
	return binary.BigEndian.Uint64(s[136:144])
}

// Get_sb_fdblocks returns free data blocks.
func (s SuperBlock) Get_sb_fdblocks() uint64 {
	return binary.BigEndian.Uint64(s[144:152])
}

// Get_sb_frextents returns free realtime extents.
func (s SuperBlock) Get_sb_frextents() uint64 {
	return binary.BigEndian.Uint64(s[152:160])
}

// Get_sb_uquotino returns inode for user quotas.
func (s SuperBlock) Get_sb_uquotino() uint64 {
	return binary.BigEndian.Uint64(s[160:168])
}

// Get_sb_gquotino returns inode for group or project quotas.
func (s SuperBlock) Get_sb_gquotino() uint64 {
	return binary.BigEndian.Uint64(s[168:176])
}

// Get_sb_qflags returns quota flags.
func (s SuperBlock) Get_sb_qflags() uint16 {
	return binary.BigEndian.Uint16(s[176:178])
}

// Get_sb_flags returns misc flags.
func (s SuperBlock) Get_sb_flags() byte {
	return s[178]
}

// Get_sb_shared_vn returns reserved, zeroed.
func (s SuperBlock) Get_sb_shared_vn() byte {
	return s[179]
}

// Get_sb_inoalignmt returns inode alignment.
func (s SuperBlock) Get_sb_inoalignmt() uint32 {
	return binary.BigEndian.Uint32(s[180:184])
}

// Get_sb_unit returns stripe or raid unit.
func (s SuperBlock) Get_sb_unit() uint32 {
	return binary.BigEndian.Uint32(s[184:188])
}

// Get_sb_width returns stripe or raid width.
func (s SuperBlock) Get_sb_width() uint32 {
	return binary.BigEndian.Uint32(s[188:192])
}

// Get_sb_dirblklog returns directory block allocation granularity.
func (s SuperBlock) Get_sb_dirblklog() byte {
	return s[192]
}

// Get_sb_logsectlog returns log sector sector size.
func (s SuperBlock) Get_sb_logsectlog() byte {
	return s[193]
}

// Get_sb_logsectsize returns log sector size.
func (s SuperBlock) Get_sb_logsectsize() uint16 {
	return binary.BigEndian.Uint16(s[194:196])
}

// Get_sb_logsunit returns log device stripe or raid unit.
func (s SuperBlock) Get_sb_logsunit() uint32 {
	return binary.BigEndian.Uint32(s[196:200])
}

// Get_sb_features2 returns additional version flags.
func (s SuperBlock) Get_sb_features2() uint32 {
	return binary.BigEndian.Uint32(s[200:204])
}

// Get_sb_bad_features2 returns mirror of sb_features2.
func (s SuperBlock) Get_sb_bad_features2() uint32 {
	return binary.BigEndian.Uint32(s[204:208])
}

// SUPERBLOCK_SIZE is the size of the SuperBlock struct.
const SUPERBLOCK_SIZE = 208
