// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by "cstruct -pkg ext -struct SuperBlock -input superblock.h -endianness LittleEndian"; DO NOT EDIT.

package ext

import "encoding/binary"

var _ = binary.LittleEndian

// SuperBlock is a byte slice representing the superblock.h C header.
type SuperBlock []byte

// Get_s_inodes_count returns s_inodes_count.
func (s SuperBlock) Get_s_inodes_count() uint32 {
	return binary.LittleEndian.Uint32(s[0:4])
}

// Get_s_blocks_count returns s_blocks_count.
func (s SuperBlock) Get_s_blocks_count() uint32 {
	return binary.LittleEndian.Uint32(s[4:8])
}

// Get_s_r_blocks_count returns s_r_blocks_count.
func (s SuperBlock) Get_s_r_blocks_count() uint32 {
	return binary.LittleEndian.Uint32(s[8:12])
}

// Get_s_free_blocks_count returns s_free_blocks_count.
func (s SuperBlock) Get_s_free_blocks_count() uint32 {
	return binary.LittleEndian.Uint32(s[12:16])
}

// Get_s_free_inodes_count returns s_free_inodes_count.
func (s SuperBlock) Get_s_free_inodes_count() uint32 {
	return binary.LittleEndian.Uint32(s[16:20])
}

// Get_s_first_data_block returns s_first_data_block.
func (s SuperBlock) Get_s_first_data_block() uint32 {
	return binary.LittleEndian.Uint32(s[20:24])
}

// Get_s_log_block_size returns s_log_block_size.
func (s SuperBlock) Get_s_log_block_size() uint32 {
	return binary.LittleEndian.Uint32(s[24:28])
}

// Get_s_magic returns s_magic.
func (s SuperBlock) Get_s_magic() []byte {
	return s[56:58]
}

// Get_s_state returns s_state.
func (s SuperBlock) Get_s_state() uint16 {
	return binary.LittleEndian.Uint16(s[58:60])
}

// Get_s_errors returns s_errors.
func (s SuperBlock) Get_s_errors() uint16 {
	return binary.LittleEndian.Uint16(s[60:62])
}

// Get_s_minor_rev_level returns s_minor_rev_level.
func (s SuperBlock) Get_s_minor_rev_level() uint16 {
	return binary.LittleEndian.Uint16(s[62:64])
}

// Get_s_lastcheck returns s_lastcheck.
func (s SuperBlock) Get_s_lastcheck() uint32 {
	return binary.LittleEndian.Uint32(s[64:68])
}

// Get_s_checkinterval returns s_checkinterval.
func (s SuperBlock) Get_s_checkinterval() uint32 {
	return binary.LittleEndian.Uint32(s[68:72])
}

// Get_s_creator_os returns s_creator_os.
func (s SuperBlock) Get_s_creator_os() uint32 {
	return binary.LittleEndian.Uint32(s[72:76])
}

// Get_s_rev_level returns s_rev_level.
func (s SuperBlock) Get_s_rev_level() uint32 {
	return binary.LittleEndian.Uint32(s[76:80])
}

// Get_s_def_resuid returns s_def_resuid.
func (s SuperBlock) Get_s_def_resuid() uint16 {
	return binary.LittleEndian.Uint16(s[80:82])
}

// Get_s_def_resgid returns s_def_resgid.
func (s SuperBlock) Get_s_def_resgid() uint16 {
	return binary.LittleEndian.Uint16(s[82:84])
}

// Get_s_first_ino returns s_first_ino.
func (s SuperBlock) Get_s_first_ino() uint32 {
	return binary.LittleEndian.Uint32(s[84:88])
}

// Get_s_inode_size returns s_inode_size.
func (s SuperBlock) Get_s_inode_size() uint16 {
	return binary.LittleEndian.Uint16(s[88:90])
}

// Get_s_block_group_nr returns s_block_group_nr.
func (s SuperBlock) Get_s_block_group_nr() uint16 {
	return binary.LittleEndian.Uint16(s[90:92])
}

// Get_s_feature_compat returns s_feature_compat.
func (s SuperBlock) Get_s_feature_compat() uint32 {
	return binary.LittleEndian.Uint32(s[92:96])
}

// Get_s_feature_incompat returns s_feature_incompat.
func (s SuperBlock) Get_s_feature_incompat() uint32 {
	return binary.LittleEndian.Uint32(s[96:100])
}

// Get_s_feature_ro_compat returns s_feature_ro_compat.
func (s SuperBlock) Get_s_feature_ro_compat() uint32 {
	return binary.LittleEndian.Uint32(s[100:104])
}

// Get_s_uuid returns s_uuid.
func (s SuperBlock) Get_s_uuid() []byte {
	return s[104:120]
}

// Get_s_volume_name returns s_volume_name.
func (s SuperBlock) Get_s_volume_name() []byte {
	return s[120:136]
}

// Get_s_last_mounted returns s_last_mounted.
func (s SuperBlock) Get_s_last_mounted() []byte {
	return s[136:200]
}

// Get_s_algorithm_usage_bitmap returns s_algorithm_usage_bitmap.
func (s SuperBlock) Get_s_algorithm_usage_bitmap() uint32 {
	return binary.LittleEndian.Uint32(s[200:204])
}

// Get_s_prealloc_blocks returns s_prealloc_blocks.
func (s SuperBlock) Get_s_prealloc_blocks() byte {
	return s[204]
}

// Get_s_prealloc_dir_blocks returns s_prealloc_dir_blocks.
func (s SuperBlock) Get_s_prealloc_dir_blocks() byte {
	return s[205]
}

// Get_s_reserved_gdt_blocks returns s_reserved_gdt_blocks.
func (s SuperBlock) Get_s_reserved_gdt_blocks() uint16 {
	return binary.LittleEndian.Uint16(s[206:208])
}

// Get_s_journal_uuid returns s_journal_uuid.
func (s SuperBlock) Get_s_journal_uuid() []byte {
	return s[208:224]
}

// Get_s_journal_inum returns s_journal_inum.
func (s SuperBlock) Get_s_journal_inum() uint32 {
	return binary.LittleEndian.Uint32(s[224:228])
}

// Get_s_journal_dev returns s_journal_dev.
func (s SuperBlock) Get_s_journal_dev() uint32 {
	return binary.LittleEndian.Uint32(s[228:232])
}

// Get_s_last_orphan returns s_last_orphan.
func (s SuperBlock) Get_s_last_orphan() uint32 {
	return binary.LittleEndian.Uint32(s[232:236])
}

// Get_s_def_hash_version returns s_def_hash_version.
func (s SuperBlock) Get_s_def_hash_version() byte {
	return s[252]
}

// Get_s_jnl_backup_type returns s_jnl_backup_type.
func (s SuperBlock) Get_s_jnl_backup_type() byte {
	return s[253]
}

// Get_s_reserved_word_pad returns s_reserved_word_pad.
func (s SuperBlock) Get_s_reserved_word_pad() uint16 {
	return binary.LittleEndian.Uint16(s[254:256])
}

// Get_s_default_mount_opts returns s_default_mount_opts.
func (s SuperBlock) Get_s_default_mount_opts() uint32 {
	return binary.LittleEndian.Uint32(s[256:260])
}

// Get_s_first_meta_bg returns s_first_meta_bg.
func (s SuperBlock) Get_s_first_meta_bg() uint32 {
	return binary.LittleEndian.Uint32(s[260:264])
}

// Get_s_mkfs_time returns s_mkfs_time.
func (s SuperBlock) Get_s_mkfs_time() uint32 {
	return binary.LittleEndian.Uint32(s[264:268])
}

// Get_s_blocks_count_hi returns s_blocks_count_hi.
func (s SuperBlock) Get_s_blocks_count_hi() uint32 {
	return binary.LittleEndian.Uint32(s[336:340])
}

// Get_s_r_blocks_count_hi returns s_r_blocks_count_hi.
func (s SuperBlock) Get_s_r_blocks_count_hi() uint32 {
	return binary.LittleEndian.Uint32(s[340:344])
}

// Get_s_free_blocks_hi returns s_free_blocks_hi.
func (s SuperBlock) Get_s_free_blocks_hi() uint32 {
	return binary.LittleEndian.Uint32(s[344:348])
}

// Get_s_min_extra_isize returns s_min_extra_isize.
func (s SuperBlock) Get_s_min_extra_isize() uint16 {
	return binary.LittleEndian.Uint16(s[348:350])
}

// Get_s_want_extra_isize returns s_want_extra_isize.
func (s SuperBlock) Get_s_want_extra_isize() uint16 {
	return binary.LittleEndian.Uint16(s[350:352])
}

// Get_s_flags returns s_flags.
func (s SuperBlock) Get_s_flags() uint32 {
	return binary.LittleEndian.Uint32(s[352:356])
}

// Get_s_raid_stride returns s_raid_stride.
func (s SuperBlock) Get_s_raid_stride() uint16 {
	return binary.LittleEndian.Uint16(s[356:358])
}

// Get_s_mmp_interval returns s_mmp_interval.
func (s SuperBlock) Get_s_mmp_interval() uint16 {
	return binary.LittleEndian.Uint16(s[358:360])
}

// Get_s_mmp_block returns s_mmp_block.
func (s SuperBlock) Get_s_mmp_block() uint64 {
	return binary.LittleEndian.Uint64(s[360:368])
}

// Get_s_raid_stripe_width returns s_raid_stripe_width.
func (s SuperBlock) Get_s_raid_stripe_width() uint32 {
	return binary.LittleEndian.Uint32(s[368:372])
}

// Get_s_checksum returns s_checksum.
func (s SuperBlock) Get_s_checksum() uint32 {
	return binary.LittleEndian.Uint32(s[1020:1024])
}

// SUPERBLOCK_SIZE is the size of the SuperBlock struct.
const SUPERBLOCK_SIZE = 1024
